//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotMinds.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Annotations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Annotations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotMinds.Resources.Annotations", typeof(Annotations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        public static string FileSizeBinarySuffix_Byte {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string FileSizeBinarySuffix_Byte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Byte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exbibyte.
        /// </summary>
        public static string FileSizeBinarySuffix_Exbibyte {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Exbibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EiB.
        /// </summary>
        public static string FileSizeBinarySuffix_Exbibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Exbibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibibyte.
        /// </summary>
        public static string FileSizeBinarySuffix_Gibibyte {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Gibibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiB.
        /// </summary>
        public static string FileSizeBinarySuffix_Gibibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Gibibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kibibyte.
        /// </summary>
        public static string FileSizeBinarySuffix_Kibibyte {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Kibibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiB.
        /// </summary>
        public static string FileSizeBinarySuffix_Kibibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Kibibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mebibyte.
        /// </summary>
        public static string FileSizeBinarySuffix_Mebibyte {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Mebibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiB.
        /// </summary>
        public static string FileSizeBinarySuffix_Mebibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Mebibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pebibyte.
        /// </summary>
        public static string FileSizeBinarySuffix_Pebibyte {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Pebibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PiB.
        /// </summary>
        public static string FileSizeBinarySuffix_Pebibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Pebibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tebibyte.
        /// </summary>
        public static string FileSizeBinarySuffix_Tebibyte {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Tebibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiB.
        /// </summary>
        public static string FileSizeBinarySuffix_Tebibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Tebibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yobibyte.
        /// </summary>
        public static string FileSizeBinarySuffix_Yobibyte {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Yobibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YiB.
        /// </summary>
        public static string FileSizeBinarySuffix_Yobibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Yobibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zebibyte.
        /// </summary>
        public static string FileSizeBinarySuffix_Zebibyte {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Zebibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZiB.
        /// </summary>
        public static string FileSizeBinarySuffix_Zebibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinarySuffix_Zebibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        public static string FileSizeDecimalSuffix_Byte {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string FileSizeDecimalSuffix_Byte_Short {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Byte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exabyte.
        /// </summary>
        public static string FileSizeDecimalSuffix_Exabyte {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Exabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EB.
        /// </summary>
        public static string FileSizeDecimalSuffix_Exabyte_Short {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Exabyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabyte.
        /// </summary>
        public static string FileSizeDecimalSuffix_Gigabyte {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Gigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string FileSizeDecimalSuffix_Gigabyte_Short {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Gigabyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobyte.
        /// </summary>
        public static string FileSizeDecimalSuffix_Kilobyte {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Kilobyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        public static string FileSizeDecimalSuffix_Kilobyte_Short {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Kilobyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabyte.
        /// </summary>
        public static string FileSizeDecimalSuffix_Megabyte {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Megabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string FileSizeDecimalSuffix_Megabyte_Short {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Megabyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petabyte.
        /// </summary>
        public static string FileSizeDecimalSuffix_Petabyte {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Petabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB.
        /// </summary>
        public static string FileSizeDecimalSuffix_Petabyte_Short {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Petabyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terabyte.
        /// </summary>
        public static string FileSizeDecimalSuffix_Terabyte {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Terabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        public static string FileSizeDecimalSuffix_Terabyte_Short {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Terabyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yottabyte.
        /// </summary>
        public static string FileSizeDecimalSuffix_Yottabyte {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Yottabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YB.
        /// </summary>
        public static string FileSizeDecimalSuffix_Yottabyte_Short {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Yottabyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zettabyte.
        /// </summary>
        public static string FileSizeDecimalSuffix_Zettabyte {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Zettabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZB.
        /// </summary>
        public static string FileSizeDecimalSuffix_Zettabyte_Short {
            get {
                return ResourceManager.GetString("FileSizeDecimalSuffix_Zettabyte_Short", resourceCulture);
            }
        }
    }
}
