//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotMinds.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Annotations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Annotations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotMinds.Resources.Annotations", typeof(Annotations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        public static string FileSizeBinaryPrefix_Byte {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string FileSizeBinaryPrefix_Byte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Byte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exbibyte.
        /// </summary>
        public static string FileSizeBinaryPrefix_Exbibyte {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Exbibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EiB.
        /// </summary>
        public static string FileSizeBinaryPrefix_Exbibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Exbibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibibyte.
        /// </summary>
        public static string FileSizeBinaryPrefix_Gibibyte {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Gibibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiB.
        /// </summary>
        public static string FileSizeBinaryPrefix_Gibibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Gibibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kibibyte.
        /// </summary>
        public static string FileSizeBinaryPrefix_Kibibyte {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Kibibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiB.
        /// </summary>
        public static string FileSizeBinaryPrefix_Kibibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Kibibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mebibyte.
        /// </summary>
        public static string FileSizeBinaryPrefix_Mebibyte {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Mebibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiB.
        /// </summary>
        public static string FileSizeBinaryPrefix_Mebibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Mebibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pebibyte.
        /// </summary>
        public static string FileSizeBinaryPrefix_Pebibyte {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Pebibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PiB.
        /// </summary>
        public static string FileSizeBinaryPrefix_Pebibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Pebibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tebibyte.
        /// </summary>
        public static string FileSizeBinaryPrefix_Tebibyte {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Tebibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiB.
        /// </summary>
        public static string FileSizeBinaryPrefix_Tebibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Tebibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yobibyte.
        /// </summary>
        public static string FileSizeBinaryPrefix_Yobibyte {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Yobibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YiB.
        /// </summary>
        public static string FileSizeBinaryPrefix_Yobibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Yobibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zebibyte.
        /// </summary>
        public static string FileSizeBinaryPrefix_Zebibyte {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Zebibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZiB.
        /// </summary>
        public static string FileSizeBinaryPrefix_Zebibyte_Short {
            get {
                return ResourceManager.GetString("FileSizeBinaryPrefix_Zebibyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        public static string FileSizePrefix_Byte {
            get {
                return ResourceManager.GetString("FileSizePrefix_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string FileSizePrefix_Byte_Short {
            get {
                return ResourceManager.GetString("FileSizePrefix_Byte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exabyte.
        /// </summary>
        public static string FileSizePrefix_Exabyte {
            get {
                return ResourceManager.GetString("FileSizePrefix_Exabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EB.
        /// </summary>
        public static string FileSizePrefix_Exabyte_Short {
            get {
                return ResourceManager.GetString("FileSizePrefix_Exabyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabyte.
        /// </summary>
        public static string FileSizePrefix_Gigabyte {
            get {
                return ResourceManager.GetString("FileSizePrefix_Gigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string FileSizePrefix_Gigabyte_Short {
            get {
                return ResourceManager.GetString("FileSizePrefix_Gigabyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobyte.
        /// </summary>
        public static string FileSizePrefix_Kilobyte {
            get {
                return ResourceManager.GetString("FileSizePrefix_Kilobyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        public static string FileSizePrefix_Kilobyte_Short {
            get {
                return ResourceManager.GetString("FileSizePrefix_Kilobyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabyte.
        /// </summary>
        public static string FileSizePrefix_Megabyte {
            get {
                return ResourceManager.GetString("FileSizePrefix_Megabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string FileSizePrefix_Megabyte_Short {
            get {
                return ResourceManager.GetString("FileSizePrefix_Megabyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petabyte.
        /// </summary>
        public static string FileSizePrefix_Petabyte {
            get {
                return ResourceManager.GetString("FileSizePrefix_Petabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB.
        /// </summary>
        public static string FileSizePrefix_Petabyte_Short {
            get {
                return ResourceManager.GetString("FileSizePrefix_Petabyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terabyte.
        /// </summary>
        public static string FileSizePrefix_Terabyte {
            get {
                return ResourceManager.GetString("FileSizePrefix_Terabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        public static string FileSizePrefix_Terabyte_Short {
            get {
                return ResourceManager.GetString("FileSizePrefix_Terabyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yottabyte.
        /// </summary>
        public static string FileSizePrefix_Yottabyte {
            get {
                return ResourceManager.GetString("FileSizePrefix_Yottabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YB.
        /// </summary>
        public static string FileSizePrefix_Yottabyte_Short {
            get {
                return ResourceManager.GetString("FileSizePrefix_Yottabyte_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zettabyte.
        /// </summary>
        public static string FileSizePrefix_Zettabyte {
            get {
                return ResourceManager.GetString("FileSizePrefix_Zettabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZB.
        /// </summary>
        public static string FileSizePrefix_Zettabyte_Short {
            get {
                return ResourceManager.GetString("FileSizePrefix_Zettabyte_Short", resourceCulture);
            }
        }
    }
}
